In [22]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

In [23]:
#load la hien thi du lieu mau, class dc gan nhan 0, 1, 2
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print('Number of classes: ',len(np.unique(iris_y)))
print('Number of the data: ',len(iris_y))

# hien thi mau tung loai du lieu
X0 = iris_X[iris_y == 0,:]
print('Sample of class 0:\n',X0[:4,:])

X1 = iris_X[iris_y == 1,:]
print('Sample of class 1:\n',X1[:4,:])

X2 = iris_X[iris_y ==2, :]
print('Sample of class 2:\n',X2[:4,:])


Number of classes:  3
Number of the data:  150
Sample of class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
Sample of class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]]
Sample of class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]]


In [24]:
# tach tap train va test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size = 50)

print('Train size: ',len(y_train))
print('Test size: ',len(y_test))

Train size:  100
Test size:  50


In [25]:
# fit du lieu va du doan voi k=1
model_1NN = neighbors.KNeighborsClassifier(n_neighbors=1,p=2)
model_1NN.fit(X_train, y_train)
y_predict = model_1NN.predict(X_test)

print('Result for 20 test:')
print('Test label:  ',y_test[:20])
print('Ground truth:',y_predict[:20])

Result for 20 test:
Test label:   [2 1 1 0 0 0 0 2 0 0 1 1 2 2 2 2 0 0 1 0]
Ground truth: [2 1 1 0 0 0 0 2 0 0 1 1 2 2 2 2 0 0 1 0]


In [26]:
# danh gia do chuan xac cua phan loai 
from sklearn.metrics import accuracy_score
print('Accuracy of 1NN: %.2f '%(100*accuracy_score(y_test, y_predict)))

Accuracy of 1NN: 96.00 


In [27]:
# model voi k=10
model_10NN = neighbors.KNeighborsClassifier(n_neighbors=10, p=2)
model_10NN.fit(X_train, y_train)
y_predict = model_10NN.predict(X_test)

print('Accuracy of 10NN: %.2f'%(100*accuracy_score(y_test,y_predict)))

Accuracy of 10NN: 98.00


In [28]:
# model voi k=10 va danh trong so cho cac dien theo khoang cach
model = neighbors.KNeighborsClassifier(n_neighbors=10, p=2, weights='distance')
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy of 10NN (weight=1/distance): %.2f'%(100*accuracy_score(y_test, y_predict)))

Accuracy of 10NN (weight=1/distance): 98.00


In [29]:
# model voi k =10 va co the hieu chinh trong so weight
def myweight(distance):
  sigma2 = .9
  return np.exp(distance**2/sigma2)

model = neighbors.KNeighborsClassifier(n_neighbors=10, p=2, weights=myweight)
model.fit(X_train, y_train)
y_predict = model.predict(X_test)
print('Accuracy of 10NN (customized weights): %.2f'%(100*accuracy_score(y_test, y_predict)))

Accuracy of 10NN (customized weights): 98.00
